nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.0.cjs

packageExtensions:
    'tailwind-variants@*':
        peerDependenciesMeta:
            tailwindcss:
                optional: true
    '@nextui-org/button@*':
        peerDependencies:
            framer-motion: '*'
    '@nextui-org/card@*':
        peerDependencies:
            framer-motion: '*'
    '@react-aria/menu@*':
        peerDependenciesMeta:
            react-dom:
                optional: true
    '@react-aria/table@*':
        peerDependenciesMeta:
            react-dom:
                optional: true
    '@react-aria/dialog@*':
        peerDependenciesMeta:
            react-dom:
                optional: true
    '@nextui-org/progress@*':
        peerDependencies:
            react-dom: '*'
    '@nextui-org/tabs@*':
        peerDependencies:
            react-dom: '*'
    '@nextui-org/react@*':
        peerDependencies:
            react-dom: '*'
