nodeLinker: node-modules

packageExtensions:
  "@nextui-org/button@*":
    peerDependencies:
      framer-motion: "*"
  "@nextui-org/card@*":
    peerDependencies:
      framer-motion: "*"
  "@nextui-org/progress@*":
    peerDependencies:
      react-dom: "*"
  "@nextui-org/react@*":
    peerDependencies:
      react-dom: "*"
  "@nextui-org/tabs@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/dialog@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@react-aria/menu@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@react-aria/table@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  tailwind-variants@*:
    peerDependenciesMeta:
      tailwindcss:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
