/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyProcessVO
 */
export interface CompanyProcessVO {
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessVO
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessVO
     */
    'equipment'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcessVO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessVO
     */
    'material'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcessVO
     */
    'processId': number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessVO
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcessVO
     */
    'viewOrder'?: number;
}

