/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerRiskStatisticDto
 */
export interface CompanyDangerRiskStatisticDto {
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'afterRiskHighCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'afterRiskLowCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'afterRiskMediumCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'currentRiskHighCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'currentRiskLowCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerRiskStatisticDto
     */
    'currentRiskMediumCount'?: number;
}

