/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactorStatisticDto } from './company-danger-factor-statistic-dto';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerRiskStatisticDto } from './company-danger-risk-statistic-dto';

/**
 * 
 * @export
 * @interface CompanyDangerReportDto
 */
export interface CompanyDangerReportDto {
    /**
     * 
     * @type {CompanyDangerFactorStatisticDto}
     * @memberof CompanyDangerReportDto
     */
    'dangerFactorStatistic'?: CompanyDangerFactorStatisticDto;
    /**
     * 
     * @type {CompanyDangerRiskStatisticDto}
     * @memberof CompanyDangerReportDto
     */
    'dangerRiskStatistic'?: CompanyDangerRiskStatisticDto;
}

