/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerSolutionExecutionDto
 */
export interface CompanyDangerSolutionExecutionDto {
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionExecutionDto
     */
    'assignee'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionExecutionDto
     */
    'companyDangerSolutionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionExecutionDto
     */
    'completionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionExecutionDto
     */
    'expectedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionExecutionDto
     */
    'method'?: CompanyDangerSolutionExecutionDtoMethodEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerSolutionExecutionDtoMethodEnum {
    Control = 'CONTROL',
    Elimination = 'ELIMINATION',
    Etc = 'ETC',
    Substitution = 'SUBSTITUTION'
}


