/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerSolutionPhoto
 */
export interface CompanyDangerSolutionPhoto {
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionPhoto
     */
    'companyDangerSolutionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhoto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhoto
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionPhoto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhoto
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhoto
     */
    'type'?: CompanyDangerSolutionPhotoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhoto
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerSolutionPhotoTypeEnum {
    Current = 'CURRENT',
    Future = 'FUTURE'
}


