/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerSolution
 */
export interface CompanyDangerSolution {
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'assignee'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolution
     */
    'companyDangerFactorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'completionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyDangerSolution
     */
    'createdByUserYn'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolution
     */
    'dangerSolutionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'expectedDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolution
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'method'?: CompanyDangerSolutionMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'type'?: CompanyDangerSolutionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolution
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerSolutionMethodEnum {
    Control = 'CONTROL',
    Elimination = 'ELIMINATION',
    Etc = 'ETC',
    Substitution = 'SUBSTITUTION'
}
/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerSolutionTypeEnum {
    Current = 'CURRENT',
    Future = 'FUTURE'
}


