/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyAdditionalInfoVO
 */
export interface CompanyAdditionalInfoVO {
    /**
     * 
     * @type {Array<string>}
     * @memberof CompanyAdditionalInfoVO
     */
    'employeeDemographyList'?: Array<CompanyAdditionalInfoVOEmployeeDemographyListEnum>;
    /**
     * 
     * @type {string}
     * @memberof CompanyAdditionalInfoVO
     */
    'environmentMeasurementYn'?: CompanyAdditionalInfoVOEnvironmentMeasurementYnEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyAdditionalInfoVO
     */
    'healthScreeningYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyAdditionalInfoVO
     */
    'processWithSpecialEducation'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyAdditionalInfoVO
     */
    'ptwRequiredYn'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompanyAdditionalInfoVO
     */
    'transportationMethodList'?: Array<CompanyAdditionalInfoVOTransportationMethodListEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompanyAdditionalInfoVO
     */
    'weightTreatmentList'?: Array<CompanyAdditionalInfoVOWeightTreatmentListEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyAdditionalInfoVOEmployeeDemographyListEnum {
    Elderly = 'ELDERLY',
    Foreign = 'FOREIGN',
    Handicapped = 'HANDICAPPED',
    Rookie = 'ROOKIE',
    Temporary = 'TEMPORARY',
    Women = 'WOMEN'
}
/**
    * @export
    * @enum {string}
    */
export enum CompanyAdditionalInfoVOEnvironmentMeasurementYnEnum {
    Doing = 'DOING',
    NotDoing = 'NOT_DOING',
    NotRequired = 'NOT_REQUIRED'
}
/**
    * @export
    * @enum {string}
    */
export enum CompanyAdditionalInfoVOTransportationMethodListEnum {
    Human = 'HUMAN',
    Machine = 'MACHINE'
}
/**
    * @export
    * @enum {string}
    */
export enum CompanyAdditionalInfoVOWeightTreatmentListEnum {
    Lift = 'LIFT',
    Pull = 'PULL',
    Push = 'PUSH'
}


