/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyProcessPhotoDto
 */
export interface CompanyProcessPhotoDto {
    /**
     * 
     * @type {number}
     * @memberof CompanyProcessPhotoDto
     */
    'companyProcessId': number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessPhotoDto
     */
    'companyProcessTitle': string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessPhotoDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessPhotoDto
     */
    'imageUrl': string;
}

