/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssessmentAdditionalInfo } from './assessment-additional-info';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyRoleStructure } from './company-role-structure';

/**
 * 
 * @export
 * @interface CompanyAssessment
 */
export interface CompanyAssessment {
    /**
     * 
     * @type {AssessmentAdditionalInfo}
     * @memberof CompanyAssessment
     */
    'additionalInfo'?: AssessmentAdditionalInfo;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'associatedInternalCorpEmployeeNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'associatedInternalCorpNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'companyAccountId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'docGeneratedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyAssessment
     */
    'docGeneratedYn'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'employeeCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'employeeNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'endAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'lastYearAccidentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'lastYearNearAccidentCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'ownerName'?: string;
    /**
     * 
     * @type {CompanyRoleStructure}
     * @memberof CompanyAssessment
     */
    'roleStructure'?: CompanyRoleStructure;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'roleStructureImageUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'sectorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'startAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'supervisor'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'supervisorPosition'?: CompanyAssessmentSupervisorPositionEnum;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'threeYearsAgoAccidentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'threeYearsAgoNearAccidentCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'twoYearsAgoAccidentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyAssessment
     */
    'twoYearsAgoNearAccidentCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'type'?: CompanyAssessmentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompanyAssessment
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyAssessmentSupervisorPositionEnum {
    Worker = 'WORKER'
}
/**
    * @export
    * @enum {string}
    */
export enum CompanyAssessmentTypeEnum {
    Continuous = 'CONTINUOUS',
    Initial = 'INITIAL',
    Regular = 'REGULAR'
}


