/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyBusinessLookUpResponse
 */
export interface CompanyBusinessLookUpResponse {
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'businessNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'businessType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'companyStartAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'corporateNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'detailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'ownerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'roadAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyBusinessLookUpResponse
     */
    'sector'?: string;
}

