/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerSolutionVORes
 */
export interface CompanyDangerSolutionVORes {
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionVORes
     */
    'dangerSolutionId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionVORes
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionVORes
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionVORes
     */
    'type'?: CompanyDangerSolutionVOResTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerSolutionVOResTypeEnum {
    Current = 'CURRENT',
    Future = 'FUTURE'
}


