/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerSolutionPhotoDto
 */
export interface CompanyDangerSolutionPhotoDto {
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhotoDto
     */
    'companyDangerFactorDescription': string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerSolutionPhotoDto
     */
    'companyDangerSolutionId': number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhotoDto
     */
    'companyDangerSolutionTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerSolutionPhotoDto
     */
    'imageUrl': string;
}

