/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyProcessTitleVO
 */
export interface CompanyProcessTitleVO {
    /**
     * 
     * @type {boolean}
     * @memberof CompanyProcessTitleVO
     */
    'doneYn'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcessTitleVO
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcessTitleVO
     */
    'title'?: string;
}

