/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerFactorVORes
 */
export interface CompanyDangerFactorVORes {
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerFactorVORes
     */
    'category'?: CompanyDangerFactorVOResCategoryEnum;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorVORes
     */
    'dangerFactorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerFactorVORes
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorVORes
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerFactorVORes
     */
    'legalDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDangerFactorVORes
     */
    'title'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum CompanyDangerFactorVOResCategoryEnum {
    Biological = 'BIOLOGICAL',
    Character = 'CHARACTER',
    Chemical = 'CHEMICAL',
    Electrical = 'ELECTRICAL',
    Environmental = 'ENVIRONMENTAL',
    Machinery = 'MACHINERY'
}


