/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerFactorStatisticDto
 */
export interface CompanyDangerFactorStatisticDto {
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'biologicalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'characterCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'chemicalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'electricalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'environmentalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorStatisticDto
     */
    'machineryCount'?: number;
}

