/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyProcess
 */
export interface CompanyProcess {
    /**
     * 
     * @type {number}
     * @memberof CompanyProcess
     */
    'assessmentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'createdAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyProcess
     */
    'createdByUserYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyProcess
     */
    'currentDangerSolutionDoneYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyProcess
     */
    'dangerFactorDoneYn'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'equipment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyProcess
     */
    'futureDangerSolutionDoneYn'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcess
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'material'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcess
     */
    'processId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcess
     */
    'sectorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyProcess
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyProcess
     */
    'viewOrder'?: number;
}

