/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyDangerFactorAfterRiskDto
 */
export interface CompanyDangerFactorAfterRiskDto {
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorAfterRiskDto
     */
    'afterRisk'?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyDangerFactorAfterRiskDto
     */
    'companyDangerFactorId'?: number;
}

