/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyProcess } from './company-process';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyProcessPhoto } from './company-process-photo';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentDangerFactorInfoDto } from './document-danger-factor-info-dto';

/**
 * 
 * @export
 * @interface DocumentProcessInfoDto
 */
export interface DocumentProcessInfoDto {
    /**
     * 
     * @type {Array<DocumentDangerFactorInfoDto>}
     * @memberof DocumentProcessInfoDto
     */
    'companyDangerFactorList'?: Array<DocumentDangerFactorInfoDto>;
    /**
     * 
     * @type {CompanyProcess}
     * @memberof DocumentProcessInfoDto
     */
    'companyProcess'?: CompanyProcess;
    /**
     * 
     * @type {Array<CompanyProcessPhoto>}
     * @memberof DocumentProcessInfoDto
     */
    'companyProcessPhotoList'?: Array<CompanyProcessPhoto>;
}

