/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactor } from './company-danger-factor';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactorPhoto } from './company-danger-factor-photo';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentDangerSolutionInfoDto } from './document-danger-solution-info-dto';

/**
 * 
 * @export
 * @interface DocumentDangerFactorInfoDto
 */
export interface DocumentDangerFactorInfoDto {
    /**
     * 
     * @type {CompanyDangerFactor}
     * @memberof DocumentDangerFactorInfoDto
     */
    'companyDangerFactor'?: CompanyDangerFactor;
    /**
     * 
     * @type {Array<CompanyDangerFactorPhoto>}
     * @memberof DocumentDangerFactorInfoDto
     */
    'companyDangerFactorPhotoList'?: Array<CompanyDangerFactorPhoto>;
    /**
     * 
     * @type {Array<DocumentDangerSolutionInfoDto>}
     * @memberof DocumentDangerFactorInfoDto
     */
    'currentCompanyDangerSolutionList'?: Array<DocumentDangerSolutionInfoDto>;
    /**
     * 
     * @type {Array<DocumentDangerSolutionInfoDto>}
     * @memberof DocumentDangerFactorInfoDto
     */
    'futureCompanyDangerSolutionList'?: Array<DocumentDangerSolutionInfoDto>;
}

