/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetCompanyAssessmentProgressResponse
 */
export interface GetCompanyAssessmentProgressResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetCompanyAssessmentProgressResponse
     */
    'currentDangerSolutionStepDoneYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCompanyAssessmentProgressResponse
     */
    'dangerFactorStepDoneYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCompanyAssessmentProgressResponse
     */
    'dangerSolutionExecutionStepDoneYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCompanyAssessmentProgressResponse
     */
    'futureDangerSolutionStepDoneYn'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetCompanyAssessmentProgressResponse
     */
    'processStepDoneYn'?: boolean;
}

