/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyAssessment } from './company-assessment';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentProcessInfoDto } from './document-process-info-dto';
// May contain unused imports in some cases
// @ts-ignore
import { Sector } from './sector';

/**
 * 
 * @export
 * @interface GetCompanyDocumentDetailInfoResponse
 */
export interface GetCompanyDocumentDetailInfoResponse {
    /**
     * 
     * @type {CompanyAssessment}
     * @memberof GetCompanyDocumentDetailInfoResponse
     */
    'companyAssessment'?: CompanyAssessment;
    /**
     * 
     * @type {Array<DocumentProcessInfoDto>}
     * @memberof GetCompanyDocumentDetailInfoResponse
     */
    'companyProcessList'?: Array<DocumentProcessInfoDto>;
    /**
     * 
     * @type {Sector}
     * @memberof GetCompanyDocumentDetailInfoResponse
     */
    'sector'?: Sector;
}

