/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyProcessVO } from './company-process-vo';
// May contain unused imports in some cases
// @ts-ignore
import { SectorVO } from './sector-vo';

/**
 * 
 * @export
 * @interface GetCompanyProcessResponse
 */
export interface GetCompanyProcessResponse {
    /**
     * 
     * @type {Array<CompanyProcessVO>}
     * @memberof GetCompanyProcessResponse
     */
    'companyProcessList'?: Array<CompanyProcessVO>;
    /**
     * 
     * @type {SectorVO}
     * @memberof GetCompanyProcessResponse
     */
    'sector': SectorVO;
}

