/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerReportDto } from './company-danger-report-dto';

/**
 * 
 * @export
 * @interface GetCompanyAssessmentReportResponse
 */
export interface GetCompanyAssessmentReportResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'assessmentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {CompanyDangerReportDto}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'dangerReport'?: CompanyDangerReportDto;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'endAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'lastUpdatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'sector'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'startAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'supervisor'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompanyAssessmentReportResponse
     */
    'title'?: string;
}

