/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyProcessPhotoDto } from './company-process-photo-dto';

/**
 * 
 * @export
 * @interface GetCompanyProcessPhotoResponse
 */
export interface GetCompanyProcessPhotoResponse {
    /**
     * 
     * @type {Array<CompanyProcessPhotoDto>}
     * @memberof GetCompanyProcessPhotoResponse
     */
    'companyProcessPhotoList'?: Array<CompanyProcessPhotoDto>;
}

