/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactorPhotoDto } from './company-danger-factor-photo-dto';

/**
 * 
 * @export
 * @interface GetCompanyDangerFactorPhotoResponse
 */
export interface GetCompanyDangerFactorPhotoResponse {
    /**
     * 
     * @type {Array<CompanyDangerFactorPhotoDto>}
     * @memberof GetCompanyDangerFactorPhotoResponse
     */
    'companyDangerFactorPhotoList'?: Array<CompanyDangerFactorPhotoDto>;
}

