/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactorDto } from './company-danger-factor-dto';

/**
 * 
 * @export
 * @interface GetCompanyDangerSolutionExecutionResponse
 */
export interface GetCompanyDangerSolutionExecutionResponse {
    /**
     * 
     * @type {Array<CompanyDangerFactorDto>}
     * @memberof GetCompanyDangerSolutionExecutionResponse
     */
    'companyDangerFactorList'?: Array<CompanyDangerFactorDto>;
}

