/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginCompanyAccountResponse
 */
export interface LoginCompanyAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginCompanyAccountResponse
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof LoginCompanyAccountResponse
     */
    'businessNumber': string;
    /**
     * 
     * @type {string}
     * @memberof LoginCompanyAccountResponse
     */
    'companyName': string;
    /**
     * 
     * @type {number}
     * @memberof LoginCompanyAccountResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof LoginCompanyAccountResponse
     */
    'ownerName': string;
    /**
     * 
     * @type {string}
     * @memberof LoginCompanyAccountResponse
     */
    'refreshTokenExpiredAt': string;
}

