/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MapVO
 */
export interface MapVO {
    /**
     * 
     * @type {string}
     * @memberof MapVO
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof MapVO
     */
    'value': string;
}

