/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MyHomeCompanyAssessmentDto
 */
export interface MyHomeCompanyAssessmentDto {
    /**
     * 
     * @type {number}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'assessmentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'docGeneratedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'docGeneratedYn'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'endAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'sector'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'startAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'supervisor'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'type'?: MyHomeCompanyAssessmentDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MyHomeCompanyAssessmentDto
     */
    'updatedAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum MyHomeCompanyAssessmentDtoTypeEnum {
    Continuous = 'CONTINUOUS',
    Initial = 'INITIAL',
    Regular = 'REGULAR'
}


