/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterCompanyAccountRequest
 */
export interface RegisterCompanyAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'baddress'?: string;
    /**
     * 사업자등록번호
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'businessNumber': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'companyName': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'detailAddress': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'email': string;
    /**
     * 
     * @type {number}
     * @memberof RegisterCompanyAccountRequest
     */
    'employeeNumber': number;
    /**
     * 대표자성명1
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'ownerName': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'postNumber': string;
    /**
     * 개업 일자
     * @type {string}
     * @memberof RegisterCompanyAccountRequest
     */
    'startDate': string;
}

