/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssessmentAdditionalInfoReq } from './assessment-additional-info-req';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyRoleStructure } from './company-role-structure';

/**
 * 
 * @export
 * @interface RegisterCompanyAssessmentAdditionalInfoRequest
 */
export interface RegisterCompanyAssessmentAdditionalInfoRequest {
    /**
     * 
     * @type {AssessmentAdditionalInfoReq}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'additionalInfo'?: AssessmentAdditionalInfoReq;
    /**
     * 사내 협력업체 수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'associatedInternalCorpCount'?: number;
    /**
     * 사내 협력업체 근로자 수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'associatedInternalCorpEmployeeCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'employeeNumber'?: number;
    /**
     * 평가 종료 기준일
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'endAt'?: string;
    /**
     * 1년 전 재해 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'lastYearAccidentCount'?: number;
    /**
     * 1년 전 아차 사고 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'lastYearNearAccidentCount'?: number;
    /**
     * 
     * @type {CompanyRoleStructure}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'roleStructure'?: CompanyRoleStructure;
    /**
     * 업종 id
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'sectorId': number;
    /**
     * 평가 시작 기준일
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'startAt'?: string;
    /**
     * 담당자
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'supervisor'?: string;
    /**
     * 담당자 직책
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'supervisorPosition'?: RegisterCompanyAssessmentAdditionalInfoRequestSupervisorPositionEnum;
    /**
     * 3년 전 재해 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'threeYearsAgoAccidentCount'?: number;
    /**
     * 3년 전 아차 사고 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'threeYearsAgoNearAccidentCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'title'?: string;
    /**
     * 2년 전 재해 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'twoYearsAgoAccidentCount'?: number;
    /**
     * 2년 전 아차 사고 발생 건수
     * @type {number}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'twoYearsAgoNearAccidentCount'?: number;
    /**
     * 보고서 종류
     * @type {string}
     * @memberof RegisterCompanyAssessmentAdditionalInfoRequest
     */
    'type'?: RegisterCompanyAssessmentAdditionalInfoRequestTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum RegisterCompanyAssessmentAdditionalInfoRequestSupervisorPositionEnum {
    Worker = 'WORKER'
}
/**
    * @export
    * @enum {string}
    */
export enum RegisterCompanyAssessmentAdditionalInfoRequestTypeEnum {
    Continuous = 'CONTINUOUS',
    Initial = 'INITIAL',
    Regular = 'REGULAR'
}


