/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Sector
 */
export interface Sector {
    /**
     * 
     * @type {string}
     * @memberof Sector
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Sector
     */
    'deletedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof Sector
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Sector
     */
    'legalCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof Sector
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Sector
     */
    'updatedAt'?: string;
}

