/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerFactorRiskDto } from './company-danger-factor-risk-dto';

/**
 * 
 * @export
 * @interface UpdateCompanyDangerFactorRiskRequest
 */
export interface UpdateCompanyDangerFactorRiskRequest {
    /**
     * 
     * @type {Array<CompanyDangerFactorRiskDto>}
     * @memberof UpdateCompanyDangerFactorRiskRequest
     */
    'companyDangerFactorRiskList'?: Array<CompanyDangerFactorRiskDto>;
}

