/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyDangerSolutionVORes } from './company-danger-solution-vores';

/**
 * 
 * @export
 * @interface UpsertCompanyDangerSolutionResponse
 */
export interface UpsertCompanyDangerSolutionResponse {
    /**
     * 
     * @type {number}
     * @memberof UpsertCompanyDangerSolutionResponse
     */
    'afterRisk': number;
    /**
     * 
     * @type {string}
     * @memberof UpsertCompanyDangerSolutionResponse
     */
    'companyDangerFactorDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpsertCompanyDangerSolutionResponse
     */
    'companyDangerFactorId': number;
    /**
     * 
     * @type {Array<CompanyDangerSolutionVORes>}
     * @memberof UpsertCompanyDangerSolutionResponse
     */
    'companyDangerSolutionList'?: Array<CompanyDangerSolutionVORes>;
    /**
     * 
     * @type {number}
     * @memberof UpsertCompanyDangerSolutionResponse
     */
    'risk': number;
}

