/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/default-api';
export * from './apis/batchapi';
export * from './apis/class1-api';
export * from './apis/class2-api';
export * from './apis/class34-api';
export * from './apis/test-controller-api';

