/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ResponseResult } from '../models';
/**
 * BATCHApi - axios parameter creator
 * @export
 */
export const BATCHApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary syncToCore
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncToCoreUsingPOST: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/batch/v1/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAUTH2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAUTH2", ["read", "write"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BATCHApi - functional programming interface
 * @export
 */
export const BATCHApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BATCHApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary syncToCore
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncToCoreUsingPOST(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncToCoreUsingPOST(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BATCHApi.syncToCoreUsingPOST']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * BATCHApi - factory interface
 * @export
 */
export const BATCHApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BATCHApiFp(configuration)
    return {
        /**
         * 
         * @summary syncToCore
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncToCoreUsingPOST(options?: any): AxiosPromise<ResponseResult> {
            return localVarFp.syncToCoreUsingPOST(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BATCHApi - object-oriented interface
 * @export
 * @class BATCHApi
 * @extends {BaseAPI}
 */
export class BATCHApi extends BaseAPI {
    /**
     * 
     * @summary syncToCore
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BATCHApi
     */
    public syncToCoreUsingPOST(options?: AxiosRequestConfig) {
        return BATCHApiFp(this.configuration).syncToCoreUsingPOST(options).then((request) => request(this.axios, this.basePath));
    }
}

