/* tslint:disable */
/* eslint-disable */
/**
 * SeWork API
 * SeWork API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ResponseResultGetCompanyProcessResponse } from '../models';
// @ts-ignore
import { ResponseResultRecommendProcessResponse } from '../models';
// @ts-ignore
import { ResponseResultUpsertCompanyProcessResponse } from '../models';
// @ts-ignore
import { UpsertCompanyProcessRequest } from '../models';
/**
 * Class1Api - axios parameter creator
 * @export
 */
export const Class1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 안전 위험 평가 1 단계 (공정) 조회
         * @summary 안전 위험 평가 1 단계 (공정) 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompanyProcessUsingGET: async (assessmentId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assessmentId' is not null or undefined
            assertParamExists('getCompanyProcessUsingGET', 'assessmentId', assessmentId)
            const localVarPath = `/api/assessment/v1/company/{assessmentId}/process`
                .replace(`{${"assessmentId"}}`, encodeURIComponent(String(assessmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAUTH2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAUTH2", ["read", "write"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 안전 위험 평가 1 단계 (공정) 추천 조회
         * @summary 안전 위험 평가 1 단계 (공정) 추천 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendProcessUsingGET: async (assessmentId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assessmentId' is not null or undefined
            assertParamExists('recommendProcessUsingGET', 'assessmentId', assessmentId)
            const localVarPath = `/api/assessment/v1/company/{assessmentId}/process/recommend`
                .replace(`{${"assessmentId"}}`, encodeURIComponent(String(assessmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAUTH2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAUTH2", ["read", "write"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 안전 위험 평가 1 단계 (공정) 수정, 입력, 삭제
         * @param {number} assessmentId assessmentId
         * @param {UpsertCompanyProcessRequest} [upsertCompanyProcessRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertCompanyProcessUsingPUT: async (assessmentId: number, upsertCompanyProcessRequest?: UpsertCompanyProcessRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assessmentId' is not null or undefined
            assertParamExists('upsertCompanyProcessUsingPUT', 'assessmentId', assessmentId)
            const localVarPath = `/api/assessment/v1/company/{assessmentId}/process`
                .replace(`{${"assessmentId"}}`, encodeURIComponent(String(assessmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAUTH2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAUTH2", ["read", "write"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertCompanyProcessRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Class1Api - functional programming interface
 * @export
 */
export const Class1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = Class1ApiAxiosParamCreator(configuration)
    return {
        /**
         * 안전 위험 평가 1 단계 (공정) 조회
         * @summary 안전 위험 평가 1 단계 (공정) 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCompanyProcessUsingGET(assessmentId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResultGetCompanyProcessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCompanyProcessUsingGET(assessmentId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['Class1Api.getCompanyProcessUsingGET']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 안전 위험 평가 1 단계 (공정) 추천 조회
         * @summary 안전 위험 평가 1 단계 (공정) 추천 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendProcessUsingGET(assessmentId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResultRecommendProcessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendProcessUsingGET(assessmentId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['Class1Api.recommendProcessUsingGET']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 안전 위험 평가 1 단계 (공정) 수정, 입력, 삭제
         * @param {number} assessmentId assessmentId
         * @param {UpsertCompanyProcessRequest} [upsertCompanyProcessRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertCompanyProcessUsingPUT(assessmentId: number, upsertCompanyProcessRequest?: UpsertCompanyProcessRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseResultUpsertCompanyProcessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertCompanyProcessUsingPUT(assessmentId, upsertCompanyProcessRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['Class1Api.upsertCompanyProcessUsingPUT']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * Class1Api - factory interface
 * @export
 */
export const Class1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = Class1ApiFp(configuration)
    return {
        /**
         * 안전 위험 평가 1 단계 (공정) 조회
         * @summary 안전 위험 평가 1 단계 (공정) 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompanyProcessUsingGET(assessmentId: number, options?: any): AxiosPromise<ResponseResultGetCompanyProcessResponse> {
            return localVarFp.getCompanyProcessUsingGET(assessmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 안전 위험 평가 1 단계 (공정) 추천 조회
         * @summary 안전 위험 평가 1 단계 (공정) 추천 조회
         * @param {number} assessmentId assessmentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendProcessUsingGET(assessmentId: number, options?: any): AxiosPromise<ResponseResultRecommendProcessResponse> {
            return localVarFp.recommendProcessUsingGET(assessmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 안전 위험 평가 1 단계 (공정) 수정, 입력, 삭제
         * @param {number} assessmentId assessmentId
         * @param {UpsertCompanyProcessRequest} [upsertCompanyProcessRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertCompanyProcessUsingPUT(assessmentId: number, upsertCompanyProcessRequest?: UpsertCompanyProcessRequest, options?: any): AxiosPromise<ResponseResultUpsertCompanyProcessResponse> {
            return localVarFp.upsertCompanyProcessUsingPUT(assessmentId, upsertCompanyProcessRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Class1Api - object-oriented interface
 * @export
 * @class Class1Api
 * @extends {BaseAPI}
 */
export class Class1Api extends BaseAPI {
    /**
     * 안전 위험 평가 1 단계 (공정) 조회
     * @summary 안전 위험 평가 1 단계 (공정) 조회
     * @param {number} assessmentId assessmentId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Class1Api
     */
    public getCompanyProcessUsingGET(assessmentId: number, options?: AxiosRequestConfig) {
        return Class1ApiFp(this.configuration).getCompanyProcessUsingGET(assessmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 안전 위험 평가 1 단계 (공정) 추천 조회
     * @summary 안전 위험 평가 1 단계 (공정) 추천 조회
     * @param {number} assessmentId assessmentId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Class1Api
     */
    public recommendProcessUsingGET(assessmentId: number, options?: AxiosRequestConfig) {
        return Class1ApiFp(this.configuration).recommendProcessUsingGET(assessmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 안전 위험 평가 1 단계 (공정) 수정, 입력, 삭제
     * @param {number} assessmentId assessmentId
     * @param {UpsertCompanyProcessRequest} [upsertCompanyProcessRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Class1Api
     */
    public upsertCompanyProcessUsingPUT(assessmentId: number, upsertCompanyProcessRequest?: UpsertCompanyProcessRequest, options?: AxiosRequestConfig) {
        return Class1ApiFp(this.configuration).upsertCompanyProcessUsingPUT(assessmentId, upsertCompanyProcessRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

