name: Deploy to Amplify Console (dev) 🚀

on:
    workflow_dispatch:
jobs:
    amplify-webhook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  curl -X POST -d {} ${{ secrets.AMPLIFY_WEBHOOK_URL_DEV }} -H
                  "Content-Type:application/json"
