name: Deploy to Amplify Console (dev) 🚀

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to deploy'
                required: true
                default: 'develop'
                type: choice
                options:
                    - master
                    - develop
jobs:
    amplify-webhook:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  curl -X POST -d {} ${{ secrets.AMPLIFY_WEBHOOK_URL_DEV }} -H "Content-Type:application/json"
