name: Test and Build before Merge

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build
